// using Microsoft.EntityFrameworkCore;
// using PgVectorDynamicRAG.Models;
// using NpgsqlTypes;

using System.Text.Json.Serialization;

namespace PgVectorDynamicRAG.Data
{
    /// <summary>
    /// Base class for the result of an embedding search
    /// used for vector, semantic and hybrid searches.
    /// </summary>
    public class EmbeddingSearchResult
    {
        /// <summary>
        /// The rank of the search result.
        /// </summary>
        public int Rank { get; set; }
        /// <summary>
        /// The score of the search result.
        /// </summary>
        public double Score { get; set; }
        /// <summary>
        /// The name of the file associated with the result.
        /// </summary>
        public string FileName { get; set; }
        /// <summary>
        /// The index of the chunk in the file.
        /// </summary>
        public int ChunkIndex { get; set; }
        /// <summary> 
        /// The definition or content of the result.
        /// </summary>
        public string Definition { get; set; }
        /// <summary>
        /// The name of the embedding model used.
        /// </summary>
        public string EmbeddingModelName { get; set; }
        /// <summary>
        /// The timestamp when the embedding was created.
        /// </summary>
        public DateTime Timestamp { get; set; }

        /// <summary>
        /// The raw image data as a Base64 encoded string.
        /// Only populated for image embedding results.
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        public string? ImageData { get; set; }

        /// <summary>
        /// Initializes a new instance of the EmbeddingSearchResult class.
        /// </summary>
        /// <param name="rank">The rank of the search result.</param>
        /// <param name="score">The score of the search result.</param>
        /// <param name="fileName">The name of the file associated with the result.</param>
        /// <param name="chunkIndex">The index of the chunk in the file.</param>
        /// <param name="definition">The definition or content of the result.</param>
        /// <param name="embeddingModelName">The name of the embedding model used.</param>
        /// <param name="timestamp">The timestamp when the embedding was created.</param>
        /// <param name="imageData">Optional Base64-encoded image data for image embedding results.</param>
        public EmbeddingSearchResult(int rank,
                                    double score,
                                    string fileName,
                                    int chunkIndex, 
                                    string definition,
                                    // string definitionEmbedding,
                                    string embeddingModelName,
                                    DateTime timestamp,
                                    string? imageData = null)
        {
            Rank = rank;
            Score = score;
            FileName = fileName;
            ChunkIndex = chunkIndex;
            Definition = definition;
            // DefinitionEmbedding = definitionEmbedding;
            EmbeddingModelName = embeddingModelName;
            Timestamp = timestamp;
            ImageData = imageData;
        }
    }

    /// <summary>
    /// Represents the context-aware chat response, which includes the results of an embedding search,
    /// the original query, and the final answer generated by the chat service.
    /// </summary>
    public class ContextAwareChatResponse
    {
        /// <summary>
        /// The search results from the embedding search.
        /// </summary>
        public List<EmbeddingSearchResult> SearchResult { get; set; }
        /// <summary>
        /// The original query string.
        /// </summary>
        public string Query { get; set; }
        /// <summary>
        /// The final answer generated by the chat service.
        /// </summary>
        public string FinalAnswer { get; set; }


        /// <summary>
        /// Initializes a new instance of the ContextAwareChatResponse class.
        /// </summary>
        /// <param name="searchResult"></param>
        /// <param name="query"></param>
        /// <param name="finalAnswer"></param>
        public ContextAwareChatResponse(List<EmbeddingSearchResult> searchResult, string query, string finalAnswer)
        {
            SearchResult = searchResult;
            Query = query;
            FinalAnswer = finalAnswer;
        }
    }
}